[package]
name = "mpl-migration-validator"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
solana-program = "=1.10"
shank = "0.0.10"
borsh = "0.9.3"
thiserror = "~1.0"
num-derive = "0.3.3"
num-traits = "~0.2"
mpl-utils = "0.0.5"
mpl-token-metadata = { version = "1.6.4", features = ["no-entrypoint"] }


[features]
test-bpf = []

[dev-dependencies]
assert_matches = "1.5.0"
solana-program-test = "=1.10"
solana-sdk = "1.10"
solana-validator = "=1.10"
solana-logger = "=1.10"

[lib]
crate-type = ["cdylib", "lib"]
